/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes } = useSpline(
    "https://prod.spline.design/CKWF1KdvY5LNUrVL/scene.splinecode"
  );
  console.log(nodes.v.material);
  console.log(nodes.dot.material);
  return (
    <>
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={2.92}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-50}
            shadow-camera-right={50}
            shadow-camera-top={50}
            shadow-camera-bottom={-50}
            position={[-13.46, 531.22, 206.03]}
            rotation={[0.1, -0.1, -2.29]}
            scale={1}
          />
          <group name="vconekt_logo " position={[-9.13, 5.42, 2.6]}>
            <mesh
              name="v"
              geometry={nodes.v.geometry}
              material={nodes.v.material}
              castShadow
              receiveShadow
              position={[-59.84, -3.14, -0.95]}
            />
            <mesh
              name="dot"
              geometry={nodes.dot.geometry}
              material={nodes.dot.material}
              receiveShadow
              position={[-99.7, 115.52, 0.6]}
            />
          </group>
          <OrthographicCamera
            name="1"
            makeDefault={true}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}
